[package]
name = "filesystem"
version = "0.1.0"
authors = ["Aofusa <5000enPCinAOFUSA@gmail.com>"]
edition = "2018"


[[bin]]
name = "main"
path = "src/main.rs"


[[bin]]
name = "data"
path = "src/data.rs"


[dependencies]
